
#server.port = 8181
server:
  port: 8181

logging:
  level:
    root: info
    com:
      example:
        apibasic:
          req: trace

# /api-docs endpoint custom path
springdoc:
  swagger-ui:
    path: /myApi.html